### ISSUE TITLE
Tracker docket in main_window.py is not yet functional

### ISSUE THREAD

**Issue by mokachokokarbon** [mokachokokarbon/Project-BET#1]
Ok. You know the title. Now you do the rest.

Tasks to be done:
- [x] add a QLineEdit on both Filing and Search dialog
- [x] add a default marker when the user doesn't use the marker
- [x] add an item in the tracker list for every newly created template
- [x] store the newly created template on a dictionary or a list
- [x] retrieve the previous template when the user double-clicked an item in the tracker list
